### ISSUE TITLE
Going to model/controller/helper/stylesheet from the template

### ISSUE THREAD

**Issue by davidmles** [textmate/ruby-on-rails-tmbundle#26]
Being in the template, the corresponding model, controller, helper or stylesheet cannot be accessed.

This can be solved editing the bundle with the integrated editor and editing `Menu Actions / Go To`, then edit `Go to Model`, `Controller`, `Helper` and `Stylesheet` this way:

Replace `text.html.erb.rails` with `text.html.erb`.

**Comment by infininight** [comment]
This works as intended if you have the "HTML (Rails)" grammar selected in the bottom of the window rather than the generic ERB grammar. Your choice will be remembered for future documents opened.

**Comment by davidmles** [comment]
I didn't notice there was a Rails HTML grammar. You are right, it works as intended.

Thanks!
